---
title: "class9"
author: "Miso Lee"
date: "May 1, 2018"
output: html_document
  html_document:
    keep_md: yes
---

## Section 1 - Preparing the data
```{r}
# importing data
wisc.df <- read.csv("WisconsinCancer.csv")
```

```{r}
# How many M's do we have
table(wisc.df$diagnosis)
```

```{r}
# Make a numeric classification vector
diagnosis <- as.numeric(wisc.df$diagnosis == "M")
table(diagnosis)
```

```{r}
# convert the features of the data: wisc.data using as.matrix()
wisc.data <- as.matrix(wisc.df[,3:ncol(wisc.df)])
```

```{r}
# set the row names of wisc.data
row.names(wisc.data) <- wisc.df$id
```

# Explatory data analysis
# The functions dim(), length(), grep(), and sum() may be useful for answering the 3 quetions

```{r}
# Q1: How many observations are in this dataset?
nrow(wisc.data)

# Q2: How many variables/features in the data are suffixed with _mean?

# return things with the word 'mean' in them
grep("mean", colnames(wisc.data), value = TRUE)

# return the position (ie index) of things with 'mean' in them
grep("mean", colnames(wisc.data), value = FALSE) # default

# return things that DON'T have the word 'mean' in them
grep("mean", colnames(wisc.data), value = TRUE, invert = TRUE)

length(grep("mean", colnames(wisc.data)))

# Q3: How many of the observations have a malignant diagnosis?
sum(diagnosis)
```

## Section 2 - Performing PCA

```{r}
# check column means and standard deviation
colMeans(wisc.data)
apply(wisc.data, 2, sd)
```

```{r}
#head(wisc.data)
wisc.data=wisc.data[,-31]
head(wisc.data)
```

```{r}
# execute PCA with the prcomp()
wisc.pr <- prcomp(wisc.data, scale = TRUE)
x <- summary(wisc.pr)
x
```

```{r}
# Q4: From your results, what proportion of the original variance is captured by the first principal components?
# 0.4427

#5: How many principal components (PCs) are required to describe at least 70% of the original variance in the data?

#Q6: How many principal components (PCs) are required to describe at least 90% of the original variance in the data?
```

# Interpreting PCA results

```{r}
# What is in our PCA output
attributes(wisc.pr)
```

```{r}
# plotting data
biplot(wisc.pr)
```

```{r}
# scatter plot observations by components 1 and 2
plot(wisc.pr$x[,1], wisc.pr$x[,2], col = (diagnosis + 1), pch = as.vector(wisc.df$diagnosis),
     xlab = "PC1", ylab = "PC2")
```

```{r}
# repeat for components 1 and 3
plot(wisc.pr$x[,c(1,3)], col = (diagnosis + 1), xlab = "PC1", ylab = "PC3")
```

# Variance explained: Screen-plot
```{r}
# caclulate viarance of each component
pr.var <- wisc.pr$sdev^2
head(pr.var)

# cumulative proportion of variance
pve <- pr.var / sum(pr.var)

# Plot cumulative proportion of variance explained
plot(pve, xlab = "Principal Component", 
     ylab = "Cumulative Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")
```

# plot as a barplot

```{r}
barplot(pve, ylab = "Percent of Variance Explained",
     names.arg=paste0("PC",1:length(pve)), las=2, axes = FALSE)

axis(2, at=pve, labels=round(pve,2)*100 )
```

# Hierarchical clustering

```{r}
# Scale the wisc.data data: data.scaled
data.scaled <- scale(wisc.data)

# Calculate distance matrix needed for hclust
data.dist <- dist(data.scaled)

# Clustering by hclust()
wisc.hclust <- hclust(data.dist)
```

```{r}
# Plotting our hclust model tree
plot(wisc.hclust)
abline(h=20, col="red")
```

```{r}
# cut into 4 clusters/groups
# wisc.hclust.clusters <- cutree(wisc.hclust, h=20)

# cutree()
wisc.hclust.clusters <- cutree(wisc.hclust, k=4)

# How many M or 1 (cancer) and 0 (non-cancer) are in each cluster
table(wisc.hclust.clusters, diagnosis)
```

```{r}
# K-means
wisc.km <- kmeans(scale(wisc.data), centers = 2, nstart = 20)

# table() function to compare the cluster membership of the k-means model (wisc.km$cluster) to the actual diagnoses contained in the diagnosis vector
table(wisc.km$cluster, diagnosis)

# table() function to compare the cluster membership of the k-means model (wisc.km$cluster) to your hierarchical clustering model from above (wisc.hclust.clusters). Recall the cluster membership of the hierarchical clustering model is contained in wisc.hclust.clusters object.
table(wisc.hclust.clusters, wisc.km$cluster)
```

## Section 5 - Clustering on PCA results

```{r}
# Creating a hierarchical clustering model with complete linkage
# Use the distance along the first 7 PCs ...
wisc.pr.hclust <- hclust(dist(wisc.pr$x[,1:7]), method = "complete")

# Cut this hierarchical clustering model into 4 clusters and assign the results to 'wisc.pr.hclust.clusters'
wisc.pr.hclust.clusters <- cutree(wisc.pr.hclust, k=4)
```

```{r}
# Using 'table()', compare the results from your new hierarchical clustering model with the actual diagnosis
table(wisc.pr.hclust.clusters, diagnosis)
```















