---
title: "class12"
author: "Miso Lee"
date: "May 10, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1.1 obtaining and inspecting our input structure
```{r}
library(bio3d)
file.name <- get.pdb("1hsg")

# read pdb structure into R
hiv <- read.pdb(file.name)
```

# 1.2 prepare initial protein and ligand input files
```{r}
prot <- trim.pdb(hiv, "protein")
lig <- trim.pdb(hiv, "ligand")

write.pdb(prot, file="1hsg_protein.pdb")
write.pdb(lig, "1hsg_ligand.pdb")
```

# 1.3 Using AutoDockTools to setup protein docking input

# 2.3 Inspecting your docking results
```{r}
res <- read.pdb("all.pdbqt", multi = TRUE)
write.pdb(res, "results.pdb")

# access the results quantitatively (calculating RMSD(root mean square distance))
ori <- read.pdb("1hsg_ligand.pdbqt")

# atom select
inds_res <- atom.select(res,"noh")
# res$xyz[,inds_res$xyz]
inds_mk <- atom.select(ori, "noh")
rmsd(ori, res$xyz[,inds_res$xyz])
```

# 5.2 Search and retrieve Adenylate kinase structures
```{r}
aa <- get.seq("p69441")

# input to the blast.pdb() function
b <- blast.pdb(aa)

# plot a summary of search results
hits <- plot(b)
```

